jobs:
  include:
    - name: HHVM 3.18
      dist: trusty
      language: php
      php: hhvm-3.18
      before_install: composer self-update --2 && travis_retry composer require "phpunit/phpunit:^5.7.27" --dev --no-update -n
      install: travis_retry composer update -n -o
      script: vendor/bin/phpunit
    - name: HHVM 3.30
      dist: trusty
      language: php
      php: hhvm-3.30
      before_install: composer self-update --2 && travis_retry composer require "phpunit/phpunit:^5.7.27" --dev --no-update -n
      install: travis_retry composer update -n -o
      script: vendor/bin/phpunit
    - name: PHP 5.4
      dist: trusty
      language: php
      php: 5.4
      before_install: composer self-update --2
      install: travis_retry composer update -n -o
      script: vendor/bin/phpunit
    - name: PHP 5.5.9
      dist: trusty
      language: php
      php: 5.5.9
      before_install: composer self-update --2
      install: travis_retry composer update -n -o
      script: vendor/bin/phpunit
    - name: PHP 5.5
      dist: trusty
      language: php
      php: 5.5
      before_install: composer self-update --2
      install: travis_retry composer update -n -o
      script: vendor/bin/phpunit
    - name: PHP 5.6
      dist: bionic
      install: travis_retry docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint composer registry.gitlab.com/grahamcampbell/php:5.6-base update -n -o
      script: docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint vendor/bin/phpunit registry.gitlab.com/grahamcampbell/php:5.6-cli
    - name: PHP 7.0
      dist: bionic
      install: travis_retry docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint composer registry.gitlab.com/grahamcampbell/php:7.0-base update -n -o
      script: docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint vendor/bin/phpunit registry.gitlab.com/grahamcampbell/php:7.0-cli
    - name: PHP 7.1
      dist: bionic
      install: travis_retry docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint composer registry.gitlab.com/grahamcampbell/php:7.1-base update -n -o
      script: docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint vendor/bin/phpunit registry.gitlab.com/grahamcampbell/php:7.1-cli
    - name: PHP 7.2
      dist: bionic
      install: travis_retry docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint composer registry.gitlab.com/grahamcampbell/php:7.2-base update -n -o
      script: docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint vendor/bin/phpunit registry.gitlab.com/grahamcampbell/php:7.2-cli
    - name: PHP 7.3
      dist: bionic
      install: travis_retry docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint composer registry.gitlab.com/grahamcampbell/php:7.3-base update -n -o
      script: docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint vendor/bin/phpunit registry.gitlab.com/grahamcampbell/php:7.3-cli
    - name: PHP 7.4
      dist: bionic
      install: travis_retry docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint composer registry.gitlab.com/grahamcampbell/php:7.4-base update -n -o
      script: docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint vendor/bin/phpunit registry.gitlab.com/grahamcampbell/php:7.4-cli
    - name: PHP 8.0
      dist: bionic
      install: travis_retry docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint composer registry.gitlab.com/grahamcampbell/php:8.0-base update -n -o --ignore-platform-req=php
      script: docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint vendor/bin/phpunit registry.gitlab.com/grahamcampbell/php:8.0-cli
